default_agent: geo_agent
agents:
  geo_agent:
    name: geo_agent
    language: python
    node_version: '20'
    entrypoint: /Users/yushengh/Documents/SA/SourceCodes/python/geoagent/src/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/yushengh/Documents/SA/SourceCodes/python/geoagent/src
    aws:
      execution_role: arn:aws:iam::023268648855:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-18a0c65da6
      execution_role_auto_create: false
      account: 023268648855
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-023268648855-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: geo_agent-XigVMZC5tE
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:023268648855:runtime/geo_agent-XigVMZC5tE
      agent_session_id: ed2b2fc2-9f18-4424-9bd4-c8291d9fae73
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: geo_agent_mem-T4wEm9Hzzp
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:023268648855:memory/geo_agent_mem-T4wEm9Hzzp
      memory_name: geo_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
