version = 0.1

[default.deploy.parameters]
stack_name = "geo-backend"
resolve_s3 = true
s3_prefix = "geo-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"geo-content\" DefaultOriginHost=\"www.setn.com\" CloudFrontDistributionArn=\"arn:aws:cloudfront::023268648855:distribution/E2ZP7RSVOE6A8D\" SetupCfOrigin=\"true\" CffArn=\"arn:aws:cloudfront::023268648855:function/geo-bot-router-oac\" CffBehaviorPath=\"*\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
